### ISSUE TITLE
`-moz-image-region` does not work on `xul:image` elements.

### ISSUE THREAD

**Issue by aubymori** [aubymori/nara-browser#4]
`xul:image` elements were previously within `nsImageBoxFrame`, however they got moved to `nsImageFrame`. While reimplementing `-moz-image-region`, I've noticed that `nsImageFrame::DidSetComputedStyle`, `nsImageFrame::PaintImage`, and `nsDisplayImage::Paint` seem to never be called. While debugging, I blanked out `nsImageFrame::PaintImage` and `nsDisplayImage::Paint`, and neither had any effect.

**Comment by kawapure** [comment]
I haven't looked into the architecture at all yet, but if a reasonably old version of Firefox put image handling in there, could we just revert it back to its original place? It might be generally beneficial.

**Comment by aubymori** [comment]
> I haven't looked into the architecture at all yet, but if a reasonably old version of Firefox put image handling in there, could we just revert it back to its original place? It might be generally beneficial.

Perhaps, yes, I tried this at one point but didn't go through with it due to `nsImageBoxFrame` not compiling with the current codebase and my laziness not fixing it.

**Comment by kawapure** [comment]
> > I haven't looked into the architecture at all yet, but if a reasonably old version of Firefox put image handling in there, could we just revert it back to its original place? It might be generally beneficial.
> 
> Perhaps, yes, I tried this at one point but didn't go through with it due to `nsImageBoxFrame` not compiling with the current codebase and my laziness not fixing it.

I added a reminder to Sunbird to look into this tomorrow, then.

**Comment by kawapure** [comment]
Fixed in d3758a3.

The fix is explained in the commit message:

> There was a small mistake regarding arguments in nsLayoutUtils.cpp. The
call should have been adjusted to use the reverted local variable `image`,
rather than the argument variable `aImage` when calling DrawImageInternal.
>
> I also cleaned up the implementation specific to nsImageFrame.cpp (which is
what handles XUL image frames since Gecko 112). The image region should now
be applied roughly around the same time as the computed style is updated.
>
> No reimplementation of nsImageBoxFrame was required for this go. I hope it
doesn't creep back up in the future, but if this was the only feature that
we needed to add it for, then it should be alright.
